import type { ScenarioData } from "../compiler/types";

export const scenario: ScenarioData = {
  tracks: [
    {
      id: "ARCLIGHT",
      actions: [
        {
          id: "ARCLIGHT_skill",
          type: "skill",
          name: "战技",
          librarySource: "character",
          element: "emag",
          duration: 1,
          cooldown: 0,
          icon: "/avatars/ARCLIGHT/icon_skill_ikut_01_line.webp",
          spCost: 100,
          gaugeCost: 0,
          gaugeGain: 6.5,
          teamGaugeGain: 6.5,
          enhancementTime: 0,
          animationTime: 0,
          damageTicks: [
            {
              offset: 0,
              sp: 0,
              stagger: 10,
              boundEffects: [],
            },
          ],
          allowedTypes: [],
          physicalAnomaly: [
            [
              {
                _id: "i5z760u",
                type: "ikut_talent",
                stacks: 1,
                duration: 0,
                offset: 0,
                sp: 0,
                stagger: 0,
              },
            ],
          ],
          weaponId: null,
          instanceId: "inst_mquf3gw",
          sourceWeaponId: null,
          logicalStartTime: 5.8,
          startTime: 5.8,
        },
      ],
      initialGauge: 0,
      maxGaugeOverride: null,
      gaugeEfficiency: 100,
      originiumArtsPower: 0,
      weaponId: null,
      weaponCommon1Tier: 1,
      weaponCommon2Tier: 1,
      weaponBuffTier: 1,
      weaponAppliedDeltas: {},
      stats: {
        primary_ability: 0,
        secondary_ability: 0,
        strength: 0,
        agility: 0,
        intellect: 0,
        will: 0,
        attack: 0,
        hp: 0,
        crit_rate: 0,
        blaze_dmg: 0,
        emag_dmg: 0,
        cold_dmg: 0,
        nature_dmg: 0,
        healing_effect: 0,
        physical_dmg: 0,
        arts_dmg: 0,
        originium_arts_power: 0,
        ult_charge_eff: 100,
        link_cd_reduction: 0,
      },
      equipArmorId: null,
      equipGlovesId: null,
      equipAccessory1Id: null,
      equipAccessory2Id: null,
      linkCdReduction: 0,
    },
    {
      id: "PERLICA",
      actions: [
        {
          id: "PERLICA_skill",
          type: "skill",
          name: "战技",
          librarySource: "character",
          element: "emag",
          duration: 0.8,
          cooldown: 0,
          icon: "/avatars/PERLICA/icon_skill_pelica_01.webp",
          spCost: 100,
          gaugeCost: 0,
          gaugeGain: 6.5,
          teamGaugeGain: 6.5,
          enhancementTime: 0,
          animationTime: 0,
          damageTicks: [
            {
              offset: 0,
              sp: 0,
              stagger: 10,
              boundEffects: [],
            },
          ],
          allowedTypes: ["emag_attach", "conductive", "emag_burst"],
          physicalAnomaly: [
            [
              {
                type: "blaze_attach",
                stacks: 1,
                duration: 0,
                _id: "y6vx7zr",
              },
            ],
            [
              {
                type: "emag_attach",
                stacks: 1,
                duration: 0,
                offset: 0.2,
                _id: "y6vx7zr1",
              },
            ],
          ],
          weaponId: null,
          instanceId: "inst_judlezw",
          sourceWeaponId: null,
          logicalStartTime: 5,
          startTime: 5,
        },
      ],
      initialGauge: 0,
      maxGaugeOverride: null,
      gaugeEfficiency: 100,
      originiumArtsPower: 0,
      weaponId: null,
      weaponCommon1Tier: 1,
      weaponCommon2Tier: 1,
      weaponBuffTier: 1,
      weaponAppliedDeltas: {},
      stats: {
        primary_ability: 0,
        secondary_ability: 0,
        strength: 0,
        agility: 0,
        intellect: 0,
        will: 0,
        attack: 0,
        hp: 0,
        crit_rate: 0,
        blaze_dmg: 0,
        emag_dmg: 0,
        cold_dmg: 0,
        nature_dmg: 0,
        healing_effect: 0,
        physical_dmg: 0,
        arts_dmg: 0,
        originium_arts_power: 0,
        ult_charge_eff: 100,
        link_cd_reduction: 0,
      },
      equipArmorId: null,
      equipGlovesId: null,
      equipAccessory1Id: null,
      equipAccessory2Id: null,
      linkCdReduction: 0,
    },
    {
      id: null,
      actions: [],
      initialGauge: 0,
      maxGaugeOverride: null,
      gaugeEfficiency: 100,
      originiumArtsPower: 0,
      weaponId: null,
      weaponCommon1Tier: 1,
      weaponCommon2Tier: 1,
      weaponBuffTier: 1,
      weaponAppliedDeltas: {},
      stats: {
        primary_ability: 0,
        secondary_ability: 0,
        strength: 0,
        agility: 0,
        intellect: 0,
        will: 0,
        attack: 0,
        hp: 0,
        crit_rate: 0,
        blaze_dmg: 0,
        emag_dmg: 0,
        cold_dmg: 0,
        nature_dmg: 0,
        healing_effect: 0,
        physical_dmg: 0,
        arts_dmg: 0,
        originium_arts_power: 0,
        ult_charge_eff: 100,
        link_cd_reduction: 0,
      },
      equipArmorId: null,
      equipGlovesId: null,
      equipAccessory1Id: null,
      equipAccessory2Id: null,
      linkCdReduction: 0,
    },
    {
      id: null,
      actions: [],
      initialGauge: 0,
      maxGaugeOverride: null,
      gaugeEfficiency: 100,
      originiumArtsPower: 0,
      weaponId: null,
      weaponCommon1Tier: 1,
      weaponCommon2Tier: 1,
      weaponBuffTier: 1,
      weaponAppliedDeltas: {},
      stats: {
        primary_ability: 0,
        secondary_ability: 0,
        strength: 0,
        agility: 0,
        intellect: 0,
        will: 0,
        attack: 0,
        hp: 0,
        crit_rate: 0,
        blaze_dmg: 0,
        emag_dmg: 0,
        cold_dmg: 0,
        nature_dmg: 0,
        healing_effect: 0,
        physical_dmg: 0,
        arts_dmg: 0,
        originium_arts_power: 0,
        ult_charge_eff: 100,
        link_cd_reduction: 0,
      },
      equipArmorId: null,
      equipGlovesId: null,
      equipAccessory1Id: null,
      equipAccessory2Id: null,
      linkCdReduction: 0,
    },
  ],
  connections: [],
  characterOverrides: {},
  weaponOverrides: {},
  equipmentCategoryOverrides: {},
  weaponStatuses: [],
  prepDuration: 5,
  prepExpanded: true,
  activeEnemyId: "custom",
  customEnemyParams: {
    maxStagger: 100,
    staggerNodeCount: 0,
    staggerNodeDuration: 2,
    staggerBreakDuration: 10,
    executionRecovery: 25,
  },
  cycleBoundaries: [],
  switchEvents: [],
};
